version: '3.8'
name: evolutionygo
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CRON_JOB_SECRET: ${CRON_JOB_SECRET}
        DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
        DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
        DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_SECRET: ${JWT_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT: ${NEXT_PUBLIC_AXIOM_INGEST_ENDPOINT}
        NEXT_PUBLIC_CACHET_API_URL: ${NEXT_PUBLIC_CACHET_API_URL}
        NEXT_PUBLIC_ONESIGNAL_APP_ID: ${NEXT_PUBLIC_ONESIGNAL_APP_ID}
        NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID: ${NEXT_PUBLIC_ONESIGNAL_SAFARI_WEB_ID}
        NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
        NODE_NO_WARNINGS: ${NODE_NO_WARNINGS}
        NX_DAEMON: ${NX_DAEMON}
        REDIS_URL: ${REDIS_URL}
        SENDGRID_API_KEY: ${SENDGRID_API_KEY}
        SENDGRID_FROM_EMAIL: ${SENDGRID_FROM_EMAIL}
        SENDGRID_PASSWORD_TEMPLATE_ID: ${SENDGRID_PASSWORD_TEMPLATE_ID}
        SENDGRID_TEMPLATE_ID: ${SENDGRID_TEMPLATE_ID}
        SERVER_API_ADMIN_KEY: ${SERVER_API_ADMIN_KEY}
        SERVER_API_URL: ${SERVER_API_URL}
    env_file: 
      - .env
    ports:
      - "3000:3000"
